@@ .. @@
     INSERT INTO auth.users (
       instance_id,
       id,
       aud,
       role,
       email,
-      encrypted_password,
+      encrypted_password,
       email_confirmed_at,
       created_at,
       updated_at,
       raw_app_meta_data,
       raw_user_meta_data,
       is_super_admin,
       confirmation_token,
       email_change,
       email_change_token_new,
       recovery_token
     ) VALUES (
       '00000000-0000-0000-0000-000000000000',
       gen_random_uuid(),
       'authenticated',
       'authenticated',
       'admin@ceramicasa.com',
-      crypt('1', gen_salt('bf')),
+      crypt('Admin1', gen_salt('bf')),
       now(),
       now(),
       now(),
       '{"provider": "email", "providers": ["email"]}',
       '{"full_name": "Administrador", "role": "admin"}',
       false,
       '',
       '',
       '',
       ''
     ) RETURNING id INTO user_id;